CREATE TABLE IF NOT EXISTS device (
	id					INTEGER PRIMARY KEY NOT NULL,
	uid					VARCHAR 16 UNIQUE NOT NULL,
	model_name			INTEGER NOT NULL,
	firmware_version	INTEGER NOT NULL,
	name				VARCHAR 32,
	when_created		INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE INDEX device_idx1 ON device(uid);
