CREATE TABLE IF NOT EXISTS firmware (
	id				INTEGER PRIMARY KEY NOT NULL,
	model_name		TEXT NOT NULL,
	version			REAL DEFAULT 0,
	description		TEXT,
	url				TEXT,
	status			TEXT NOT NULL DEFAULT "new",
	created_at	INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at	INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
);