CREATE TABLE IF NOT EXISTS model(
	id				INTEGER PRIMARY KEY NOT NULL,
	name			TEXT UNIQUE NOT NULL,
	description		TEXT,
	manufacturer	TEXT,
	datasheet		TEXT,
	created_at	INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at	INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
);