CREATE TABLE IF NOT EXISTS object(
	id INTEGER PRIMARY KEY NOT NULL,
	project_id INTEGER UNIQUE NOT NULL ,
	name TEXT UNIQUE NOT NULL ,
	type TEXT NOT NULL DEFAULT 'generic',
	visible INTEGER NOT NULL ,
	status TEXT NOT NULL DEFAULT 'new',
	created_at INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
);