CREATE TABLE IF NOT EXISTS sector_item(
	id				INTEGER PRIMARY KEY NOT NULL,
	sector_id		INTEGER NOT NULL,
	item_id			INTEGER NOT NULL,
	name			TEXT UNIQUE NOT NULL,
	type			VARCHAR 32,
	active			INTEGER DEFAULT 0,
	created_at	INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
	FOREIGN KEY (sector_id) REFERENCES sector(id)
);